name: Go Docker CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./... -v

    - name: Build Docker image
      run: docker build -t go-docker-demo .

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go-docker-demo:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/go-docker-demo:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go-docker-demo:latest
          docker stop go-docker-demo || true
          docker rm go-docker-demo || true
          docker run -d --name go-docker-demo -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/go-docker-demo:latest
#